sudo: required
services:
  - Docker

before_install:
  - docker build -t parag1201/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true parag1201/react-test npm test -- --coverage

after_success:
  - docker build -t parag1201/multi-client ./client
  - docker build -t parag1201/multi-server ./server
  - docker build -t parag1201/multi-worker ./worker
  - docker build -t parag1201/multi-nginx ./nginx
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push parag1201/multi-client
  - docker push parag1201/multi-server
  - docker push parag1201/multi-worker
  - docker push parag1201/multi-nginx 
  